"""planes / mensajes / facturas / pagos – billing & Flow (issue #7)

Revision ID: 0003_planes_facturas_pagos
Revises: 0002_clientes
Create Date: 2026-06-27 00:00:00.000000

Creates the four tables that back the billing & Flow integration
(issue #7):

- ``planes``    – the catalog of plans the customer can
  subscribe to. Mirrors :class:`app.models.plan.Plan`.
- ``mensajes``  – the per-message ledger the billing service
  aggregates over. Mirrors :class:`app.models.message.Message`.
- ``facturas``  – the electronic invoices the platform
  issues. Mirrors :class:`app.models.invoice.Invoice`.
- ``pagos``     – the Flow payment records the platform
  maintains while waiting for the asynchronous confirmation
  webhook. Mirrors :class:`app.models.payment.Payment`.

The downgrade drops the four tables. There is no data to
preserve: a fresh ``alembic upgrade head`` against a clean
database will recreate them identically.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_planes_facturas_pagos"
down_revision: Union[str, Sequence[str], None] = "0002_clientes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the planes / mensajes / facturas / pagos tables."""
    # ------------------------------------------------------------------
    # planes
    # ------------------------------------------------------------------
    op.create_table(
        "planes",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("price_clp", sa.Integer(), nullable=False),
        sa.Column("msg_limit", sa.Integer(), nullable=True),
        sa.Column("extra_msg_price", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="100"),
        sa.Column("billing_period", sa.String(length=20), nullable=False, server_default="monthly"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("code", name="uq_planes_code"),
    )
    op.create_index("ix_planes_code", "planes", ["code"], unique=True)

    # Seed the MVP catalog (Starter / Growth / Enterprise) so
    # ``POST /v1/billing/subscriptions`` and the ``default
    # plan`` resolution in the registration flow have rows to
    # refer to immediately after ``alembic upgrade head``.
    op.bulk_insert(
        sa.table(
            "planes",
            sa.column("id", sa.String),
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("description", sa.String),
            sa.column("price_clp", sa.Integer),
            sa.column("msg_limit", sa.Integer),
            sa.column("extra_msg_price", sa.Integer),
            sa.column("active", sa.Boolean),
            sa.column("sort_order", sa.Integer),
            sa.column("billing_period", sa.String),
        ),
        [
            # ``id`` is generated client-side by
            # :meth:`Plan.__init__`; the migration hard-codes
            # the values so a re-run of the migration is
            # deterministic (the rows are not regenerated by
            # autogenerate).
            {
                "id": "00000000-0000-0000-0000-000000000001",
                "code": "starter",
                "name": "Starter",
                "description": "1.000 mensajes al mes, ideal para emprendedores.",
                "price_clp": 19990,
                "msg_limit": 1000,
                "extra_msg_price": 25,
                "active": True,
                "sort_order": 10,
                "billing_period": "monthly",
            },
            {
                "id": "00000000-0000-0000-0000-000000000002",
                "code": "growth",
                "name": "Growth",
                "description": "10.000 mensajes al mes, soporte prioritario.",
                "price_clp": 79990,
                "msg_limit": 10000,
                "extra_msg_price": 18,
                "active": True,
                "sort_order": 20,
                "billing_period": "monthly",
            },
            {
                "id": "00000000-0000-0000-0000-000000000003",
                "code": "enterprise",
                "name": "Enterprise",
                "description": "Volumen ilimitado, precio a medida. Contáctanos.",
                "price_clp": 0,
                "msg_limit": None,
                "extra_msg_price": None,
                "active": True,
                "sort_order": 30,
                "billing_period": "monthly",
            },
        ],
    )

    # ------------------------------------------------------------------
    # mensajes
    # ------------------------------------------------------------------
    op.create_table(
        "mensajes",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("to_hash", sa.String(length=64), nullable=False),
        sa.Column("body", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="queued"),
        sa.Column("provider_msg_id", sa.String(length=128), nullable=True),
        sa.Column("cost_clp", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fee_clp", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_mensajes_client_id", "mensajes", ["client_id"])
    op.create_index("ix_mensajes_channel", "mensajes", ["channel"])
    op.create_index("ix_mensajes_to_hash", "mensajes", ["to_hash"])
    op.create_index("ix_mensajes_status", "mensajes", ["status"])
    op.create_index("ix_mensajes_created_at", "mensajes", ["created_at"])

    # ------------------------------------------------------------------
    # facturas
    # ------------------------------------------------------------------
    op.create_table(
        "facturas",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("number", sa.String(length=32), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("plan_code", sa.String(length=32), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("total_msgs", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("included_msgs", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("overage_msgs", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("subtotal_clp", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("iva_clp", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_clp", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("dte_number", sa.Integer(), nullable=True),
        sa.Column("dte_url", sa.String(length=500), nullable=True),
        sa.Column("flow_invoice_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="draft"),
        sa.Column("tipo", sa.String(length=32), nullable=False, server_default="factura_electronica"),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("number", name="uq_facturas_number"),
        sa.UniqueConstraint("dte_number", name="uq_facturas_dte_number"),
    )
    op.create_index("ix_facturas_number", "facturas", ["number"], unique=True)
    op.create_index("ix_facturas_client_id", "facturas", ["client_id"])
    op.create_index("ix_facturas_plan_id", "facturas", ["plan_id"])
    op.create_index("ix_facturas_status", "facturas", ["status"])

    # ------------------------------------------------------------------
    # pagos
    # ------------------------------------------------------------------
    op.create_table(
        "pagos",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("invoice_id", sa.String(length=36), nullable=True),
        sa.Column("plan_code", sa.String(length=32), nullable=False),
        sa.Column("amount_clp", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("flow_token", sa.String(length=128), nullable=False),
        sa.Column("flow_order", sa.String(length=64), nullable=False),
        sa.Column("flow_payment_id", sa.String(length=64), nullable=True),
        sa.Column("flow_redirect_url", sa.String(length=500), nullable=True),
        sa.Column("flow_response", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("flow_token", name="uq_pagos_flow_token"),
    )
    op.create_index("ix_pagos_flow_token", "pagos", ["flow_token"], unique=True)
    op.create_index("ix_pagos_flow_order", "pagos", ["flow_order"])
    op.create_index("ix_pagos_client_id", "pagos", ["client_id"])
    op.create_index("ix_pagos_invoice_id", "pagos", ["invoice_id"])
    op.create_index("ix_pagos_status", "pagos", ["status"])


def downgrade() -> None:
    """Drop the four billing tables."""
    op.drop_index("ix_pagos_status", table_name="pagos")
    op.drop_index("ix_pagos_invoice_id", table_name="pagos")
    op.drop_index("ix_pagos_client_id", table_name="pagos")
    op.drop_index("ix_pagos_flow_order", table_name="pagos")
    op.drop_index("ix_pagos_flow_token", table_name="pagos")
    op.drop_table("pagos")

    op.drop_index("ix_facturas_status", table_name="facturas")
    op.drop_index("ix_facturas_plan_id", table_name="facturas")
    op.drop_index("ix_facturas_client_id", table_name="facturas")
    op.drop_index("ix_facturas_number", table_name="facturas")
    op.drop_table("facturas")

    op.drop_index("ix_mensajes_created_at", table_name="mensajes")
    op.drop_index("ix_mensajes_status", table_name="mensajes")
    op.drop_index("ix_mensajes_to_hash", table_name="mensajes")
    op.drop_index("ix_mensajes_channel", table_name="mensajes")
    op.drop_index("ix_mensajes_client_id", table_name="mensajes")
    op.drop_table("mensajes")

    op.drop_index("ix_planes_code", table_name="planes")
    op.drop_table("planes")
